---
- type: bakery
  name: Выпечка
  values: [пирожки с яйцом и луком, пирожки с яблоком, слойки с вишней, шарлотка, слойки с яблоком и корицей, манник, печенье сдобное, кекс, чебуреки, пирог с персиками]
  count: 1

- type: breakfasts
  name: Завтраки
  values: [блины, оладьи, сырники, манная каша, овсяная каша, йогурт, бекон, глазунья, скрембл с помидорами, пшеничная каша, консервированные ягоды, свежие ягоды, консервированные фрукты, свежие фрукты, ветчина, сосиски,  горошек, гренки, горячие тосты с джемом, хлопья с молоком, хлопья с йогуртом, омлет, творог, творожная масса, сырники]
  count: 7

- type: dishes
  name: Основные блюда
  values: [плов, лагман, окрошка, картошка жареная, картошка с селёдкой, варёная кукуруза, капуста тушёная, курица с картошкой в духовке, запеканка гороховая каша с мясом, пельмени, чахохбили, рагу]
  count: 2

- type: fregetables
  name: Фрукты и овощи
  values: [бананы, грейпфруты, апельсины, мандарины, яблоки, груши, виноград, киви, авокадо, персики, хурма, сливы, ягоды по сезону, абрикосы, нектарины]
  count: 2

- type: garnishes
  name: Гарниры
  values: [пюре, гречка, рис, макароны, свежие овощи, заморозка овощная, лапша, ячневая]
  count: 1

- type: meat
  name: Мясо
  values: [стейки, котлеты, рыба белая, рыба красная, гуляш, куриные берда, куриные крылья, куриные ноги, куриная грудка, бефстроганов, креветки, ветчина, сосиски, сардельки, кролик, утка]
  count: 1

- type: salads
  name: Салаты
  values: [Огурцы-помидоры, коул-слоу, Свёкла с чесноком и орехами, капустный салат витаминный с морковкой/яблоком, крабовый, селёдка под шубой, оливье, с картошкой и яйцом, греческий, винегрет]
  count: 1

- type: soups
  name: Супы
  values: [борщ, щи, гороховый, солянка, уха по-фински, крем-суп из чечевицы, суп из рыбной консервы, куриная лапша]
  count: 2